name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to ECS
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.27.221.124 << 'EOF'
            cd /home/ec2-user/News-Blog-Postal
            git pull origin main
            npm install
            pm2 restart news-portal || pm2 start app.js --name "news-portal"
            pm2 save
          EOF
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
